
USE bookticket;

ALTER TABLE SanPham ADD COLUMN SoLuong INT DEFAULT 0;
ALTER TABLE SanPham ADD COLUMN TrangThai VARCHAR(10) DEFAULT 'Con hang';

ALTER TABLE SanPham MODIFY COLUMN HinhAnh VARCHAR(255);
ALTER TABLE SanPham MODIFY COLUMN TenSanPham VARCHAR(100);
